version: '3.0'
services:
  climkit-to-mqtt:
    image: gaetancollaud/climkit-to-mqtt:dev
    build: .
    environment:
      - MQTT_URL=tcp://mosquitto:1883
    env_file:
      - .env

  mosquitto:
    image: eclipse-mosquitto:1.5
    volumes:
      - ./docs/docker/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    ports:
      - "1883:1883"
      - "9001:9001"

  postgres:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
