POST https://api.climkit.io/api/v1/auth
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}

> {%
    client.global.set("token", JSON.parse(response.body).access_token);

    client.log(response.body)
    client.log(JSON.parse(response.body).access_token)
    client.log(client.global.get("token"))
%}

### get all sites
GET https://api.climkit.io/api/v1/all_installations
Content-Type: application/json
Authorization: Bearer {{token}}

### Site info
GET https://api.climkit.io/api/v1/installation_infos/{{installationId}}
Content-Type: application/json
Authorization: Bearer {{token}}


### Meters info
GET https://api.climkit.io/api/v1/meter_info/{{installationId}}
Content-Type: application/json
Authorization: Bearer {{token}}


### Meters timeseries (JSON)
POST https://api.climkit.io/api/v1/site_data/{{installationId}}/electricity
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "t_s": "2022-07-18 20:00:00"
}

### meter value (for one meter)
POST https://api.climkit.io/api/v1/meter_data/{{installationId}}/{{noAccessMeterId}}
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "t_s": "2022-07-27T12:00:00",
  "t_e": "2022-07-27T13:00:00"
}

### raw meter value
POST https://api.climkit.io/api/v1/meter_data_raw/{{installationId}}/{{oneMeterId}}
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "t_s": "2022-07-27T17:00:00"
}

### sensor list
GET https://api.climkit.io/api/v1/{{installationId}}/sensors_list
Accept: application/json
Authorization: Bearer {{token}}



