POST https://api.climkit.io/api/v1/auth
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}

> {%
    client.global.set("token", JSON.parse(response.body).access_token);

    client.log(response.body)
    client.log(JSON.parse(response.body).access_token)
    client.log(client.global.get("token"))
%}

### get all sites
GET https://api.climkit.io/api/v1/all_installations
Content-Type: application/json
Authorization: Bearer {{token}}

### Site info
GET https://api.climkit.io/api/v1/installation_infos/61dfca84eba4e3564021f366
Content-Type: application/json
Authorization: Bearer {{token}}


### Meters info
GET https://api.climkit.io/api/v1/meter_info/61dfca84eba4e3564021f366
Content-Type: application/json
Authorization: Bearer {{token}}


### Meters timeseries
POST https://api.climkit.io/api/v1/site_data/61dfca84eba4e3564021f366/electricity
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "t_s": "2022-05-20T00:00:00Z"
}


### raw meter value
POST https://api.climkit.io/api/v1/meter_data_raw/61dfca84eba4e3564021f366/61dfcb4beba4e3563fdf3d9f
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "t_s": "2022-05-20T15:00:00Z"
}

